In [1]:
import pandas as pd
from numpy.random import random, randint, normal, shuffle, choice as randchoice

In [3]:
path = "/Users/Richard/PsychoPy_1/SNORE/Nature/encoding/supplementary/lists/nature_words_final.xlsx"

df = pd.read_excel(path)

df.head()

,Word1,WORD_length1,Emo_condition,length_group_emo,Word2,WORD_length2,Ima_condition,length_group_ima,Randomize
0,Apfel,NaN,NaN,NaN,Lilie,NaN,NaN,NaN,False
1,Eisbär,NaN,NaN,NaN,Palme,NaN,NaN,NaN,False
2,Lerche,NaN,NaN,NaN,Biber,NaN,NaN,NaN,False
3,Spore,5.0,emo_mid,short_word,Bulle,5.0,ima_high,short_word,True
4,Kiwi,4.0,emo_mid,short_word,Reptil,6.0,ima_high,short_word,True

In [4]:
first_3 = df[:3]
first_3

,Word1,WORD_length1,Emo_condition,length_group_emo,Word2,WORD_length2,Ima_condition,length_group_ima,Randomize
0,Apfel,NaN,NaN,NaN,Lilie,NaN,NaN,NaN,False
1,Eisbär,NaN,NaN,NaN,Palme,NaN,NaN,NaN,False
2,Lerche,NaN,NaN,NaN,Biber,NaN,NaN,NaN,False

In [7]:
random_list = df[3:39]
random_list

,Word1,WORD_length1,Emo_condition,length_group_emo,Word2,WORD_length2,Ima_condition,length_group_ima,Randomize
3,Spore,5.0,emo_mid,short_word,Bulle,5.0,ima_high,short_word,True
4,Kiwi,4.0,emo_mid,short_word,Reptil,6.0,ima_high,short_word,True
5,Hafer,5.0,emo_mid,short_word,Gras,4.0,ima_high,short_word,True
6,Sprosse,7.0,emo_mid,long_word,Brombeere,9.0,ima_high,long_word,True
7,Lorbeer,7.0,emo_mid,long_word,Walnuss,7.0,ima_high,long_word,True
8,Rohr,4.0,emo_mid,short_word,Larve,5.0,ima_high,short_word,True
9,Boxer,5.0,emo_mid,short_word,Frucht,6.0,ima_high,short_word,True
10,Zwiebel,7.0,emo_mid,long_word,Faultier,8.0,ima_high,long_word,True
11,Knoblauch,9.0,emo_mid,long_word,Spargel,7.0,ima_high,long_word,True
12,Senf,4.0,emo_mid,short_word,Amsel,5.0,ima_high,short_word,True
13,Nashorn,7.0,emo_mid,long_word,Weißkohl,8.0,ima_high,long_word,True
14,Raupe,5.0,emo_mid,short_word,Fisch,5.0,ima_high,short_word,True
15,Kardinal,8.0,emo_mid,long_word,Sellerie,8.0,ima_high,long_word,True
16,Lurch,5.0,emo_mid,short_word,Ratte,5.0,ima_high,short_word,True
17,Maulwurf,8.0,emo_mid,long_word,Karpfen,7.0,ima_high,long_word,True
18,Käfer,5.0,emo_mid,short_word,Hengst,6.0,ima_high,short_word,True
19,Barsch,6.0,emo_mid,short_word,Tiger,5.0,ima_high,short_word,True
20,Geier,5.0,emo_mid,short_word,Motte,5.0,ima_high,short_word,True
21,Busch,5.0,emo_mid,short_word,Krähe,5.0,ima_high,short_word,True
22,Habicht,7.0,emo_mid,long_word,Blutegel,8.0,ima_high,long_word,True
23,Vieh,4.0,emo_mid,short_word,Pfau,4.0,ima_high,short_word,True
24,Languste,8.0,emo_mid,long_word,Getreide,8.0,ima_high,long_word,True
25,Gorilla,7.0,emo_mid,long_word,Seepferd,8.0,ima_high,long_word,True
26,Gaul,4.0,emo_mid,short_word,Ei,2.0,ima_high,short_word,True
27,Zeder,5.0,emo_mid,short_word,Ente,4.0,ima_high,short_word,True
28,Walross,7.0,emo_mid,long_word,Schlange,8.0,ima_high,long_word,True
29,Dromedar,8.0,emo_mid,long_word,Rosenkohl,9.0,ima_high,long_word,True
30,Wolf,4.0,emo_mid,short_word,Buche,5.0,ima_high,short_word,True
31,Kolibri,7.0,emo_mid,long_word,Thunfisch,9.0,ima_high,long_word,True
32,Säugetier,9.0,emo_mid,long_word,Fledermaus,10.0,ima_high,long_word,True
33,Quitte,6.0,emo_mid,short_word,Bock,4.0,ima_high,short_word,True
34,Eidechse,8.0,emo_mid,long_word,Stinktier,9.0,ima_high,long_word,True
35,Strauch,7.0,emo_mid,long_word,Rebhuhn,7.0,ima_high,long_word,True
36,Mammut,6.0,emo_mid,short_word,Otter,5.0,ima_high,short_word,True
37,Krokodil,8.0,emo_mid,long_word,Seeigel,7.0,ima_high,long_word,True
38,Raubtier,8.0,emo_mid,long_word,Wildkatze,9.0,ima_high,long_word,True

In [9]:
last_3 = df[39:]
last_3

,Word1,WORD_length1,Emo_condition,length_group_emo,Word2,WORD_length2,Ima_condition,length_group_ima,Randomize
39,Hund,NaN,NaN,NaN,Farn,NaN,NaN,NaN,False
40,Kobra,NaN,NaN,NaN,Made,NaN,NaN,NaN,False
41,Laus,NaN,NaN,NaN,Wanze,NaN,NaN,NaN,False

In [11]:
shuffle(random_list)

/var/folders/jz/fzhqjtjs2qs1vdhm2p0k6mpm0000gn/T/ipykernel_62171/1441441902.py:1: UserWarning: you are shuffling a 'DataFrame' object which is not a subclass of 'Sequence'; `shuffle` is not guaranteed to behave correctly. E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
  shuffle(random_list)

KeyError: 8